apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebridge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://geek-cookbook.github.io/charts/
    targetRevision: 1.0.5
    chart: homebridge
    helm:
      valuesObject:
        podAnnotations:
          k8s.v1.cni.cncf.io/networks: default/br-multus
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          storageClass: ceph-block
          size: 1Gi
        timezone: "America/New York"
        ingress:
          enabled: true
          ingressClassName: "nginx" # "nginx"
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          hosts:
          -  homebridge.mershab.com
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - priority=8
  destination:
    name: loft-homelab-vcluster-dad
    namespace: homebridge
