apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dad-multus
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: https://github.com/Mershab99/homebase.git
    targetRevision: "v1" #Based on environment
    path: 'resources/apps/multus/'
    directory:
      recurse: false
  destination:
    name: loft-homelab-vcluster-dad
    namespace: multus
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - priority=7
      - allowEmpty=true
      - skipDryRunOnMissingResource=true
      - ServerSideApply=true
