apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dad-mysql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.0.0
    chart: mysql
    helm:
      valuesObject:

        primary:
          service:
            type: LoadBalancer

        image:
          tag: 8.0.32

        auth:
          rootPassword: Fahimm123
          database: "winnersdb"
          username: "admin"
          password: "xxx"

        primary:
          persistence:
            enabled: true
            #existingClaim: "mysql-pvc"

        volumePermissions:
          enabled: true

        initdbScripts:
          init_db.sql: |
            CREATE DATABASE novmar;
            CREATE DATABASE winners;



  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - priority=8
      - allowEmpty=true
      - skipDryRunOnMissingResource=true
      - ServerSideApply=true
  destination:
    name: loft-homelab-vcluster-dad
    namespace: mysql
