apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mershab-git-repo-stats
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Mershab99/git-repo-stats.git'
    targetRevision: main
    path: 'charts/git-repo-stats'
    helm:
#      parameters:
#        - name: someParameter
#          value: someValue
      values: |
        image:
          repository: ghcr.io/mershab99/git-repo-stats
          pullPolicy: Always
          # Overrides the image tag whose default is the chart appVersion.
          tag: "latest"
        service:
          type: ClusterIP
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
            #nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          hosts:
            - host: git-repo-stats.mershab.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
  destination:
    name: loft-homelab-vcluster-mershab
    namespace: git-repo-stats
  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - priority=8
      - allowEmpty=true
      - skipDryRunOnMissingResource=true
      - ServerSideApply=true
