apiVersion: batch/v1
kind: Job
metadata:
  name: rclone-transfer-job-movies
  namespace: mediaserver
spec:
  template:
    spec:
      hostNetwork: true
      restartPolicy: OnFailure  # Ensures the job retries if it fails
      containers:
      - name: rclone-container
        image: rclone/rclone:latest  # Rclone image to perform the file transfer
        command: ["/bin/sh", "-c"]
        args:
          - |
            rclone copy /mnt/mediavault/media/movies /mnt/pv/media/movies --ignore-existing --transfers=4 --checkers=16 --progress &&
            echo "File transfer Movies completed."
        volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/mediavault  # NFS mount
        - name: pvc-volume
          mountPath: /mnt/pv  # PV mount
      volumes:
      - name: nfs-volume
        nfs:
          server: 192.168.2.205  # Replace with your NFS server IP
          path: /mnt/vault/mediavault  # NFS export path
      - name: pvc-volume
        persistentVolumeClaim:
          claimName: mediaserver-pvc  # PVC reference for the PV
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rclone-transfer-job-tv
  namespace: mediaserver
spec:
  template:
    spec:
      hostNetwork: true
      restartPolicy: OnFailure  # Ensures the job retries if it fails
      containers:
      - name: rclone-container
        image: rclone/rclone:latest  # Rclone image to perform the file transfer
        command: ["/bin/sh", "-c"]
        args:
          - |
            rclone copy /mnt/mediavault/media/tv /mnt/pv/media/shows --ignore-existing --transfers=8 --checkers=16 --progress &&
            echo "File transfer TV Shows completed."
        volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/mediavault  # NFS export path
        - name: pvc-volume
          mountPath: /mnt/pv  # PV mount
      volumes:
      - name: nfs-volume
        nfs:
          server: 192.168.2.205  # Replace with your NFS server IP
          path: /mnt/vault/mediavault  # NFS export path
      - name: pvc-volume
        persistentVolumeClaim:
          claimName: mediaserver-pvc  # PVC reference for the PV
