apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod-dr
  namespace: dr
spec:
  hostNetwork: true
  containers:
  - name: ubuntu-container
    securityContext:
      privileged: true
    image: ubuntu  # The Ubuntu image for your container
    command: ["/bin/sh", "-c", "sleep infinity"]  # Keeps the container running for testing
    volumeMounts:
    - name: node-var
      mountPath: /node/var/lib/  # Path inside the container for the NFS mount
  volumes:
  - name: node-var
    hostPath:
      path: /var/lib/
