apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://pajikos.github.io/home-assistant-helm-chart
    targetRevision: 0.2.82
    chart: home-assistant
    helm:
      valuesObject:
        hostNetwork: true
        env:
         - name: TZ
           value: "America/New York"
        podAnnotations:
            k8s.v1.cni.cncf.io/networks: flat-network
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          hosts:
          - host: velvet.mershab.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        configuration:
          enabled: true

  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - priority=8
  destination:
    name: loft-main-vcluster-home
    namespace: homeassistant
