apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebridge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://geek-cookbook.github.io/charts/
    targetRevision: 5.3.2
    chart: homebridge
    helm:
      valuesObject:
        persistence:
          config:
            enabled: true
            accessMode: ReadWriteOnce
            storageClass: ceph-block
            size: 1Gi
        hostNetwork: true
        env:
         - name: TZ
           value: "America/New York"
        ingress:
          main:
            enabled: true
            ingressClassName: "nginx" # "nginx"
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            hosts:
            - host: homebridge.mershab.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
        configmap:
          scripts:
            enabled: true
#            data:
#              # -- Custom homebridge startup script contents
#              # @default -- See values.yaml
#              startup.sh: |
#                #!/bin/sh
#
#                #
#                # Docker Homebridge Custom Startup Script - oznu/homebridge
#                #
#                # This script can be used to customise the environment and will be executed as
#                # the root user each time the container starts.
#                #
#                # If using this to install plugins DO NOT use the global flag (-g).
#                #
#                # Example installing homebridge plugin:
#                #
#                # npm install homebridge-hue
#                #
#                # Example installing packages using default image (Alpine Linux):
#                #
#                # apk add --no-cache ffmpeg ffmpeg-libs libpcap-dev
#                #
#                # If you're running a debian based version of this container please use apt-get to install packages.
#                #
#                echo "Started successfully."

  syncPolicy:
    automated: 
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - priority=8
  destination:
    name: loft-main-vcluster-home
    namespace: homebridge
