apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: flat-network
  namespace: homeassistant
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eno1",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": [
        { "address": "192.168.2.215/32", "gateway": "192.168.2.1" }
      ]
    }
    }'
