
ingress:
  ingressClassName: "nginx" # "nginx"
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Specifies the ingress controller class
      #nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      #nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

  hosts:
  - host: langflow.mershab.com
    paths:
      - path: /
